### ISSUE TITLE
Example IOC fails to build on Windows

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorHytec#3]
The example IOC fails to build on Windows because of the change in this pull request: https://github.com/epics-motor/motorHytec/pull/2

**Comment by MarkRivers** [comment]
This file iocs/hytecIOC/hytecApp/src/Makefile should be changed to only build the example IOC on Linux and vxWorks.  The Hytec driver will never work on Windows because there won't be an Industry Pack carrier card driver.

**Comment by kmpeters** [comment]
I'm working on that now.  My windows machine is slow.
